version: '3'
services:
  express-app:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - flask-app
      - redis
      - mongo
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://mongo:27017/AIsummarizer
      - REDISHOST=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./server/.env
    command: yarn run start:dev

  flask-app:
    build: ./python-youtube-scraper
    volumes:
      - ./python-youtube-scraper:/usr/src/app

  redis:
    image: "redis:latest"
    ports:
      - "6381:6379"

  mongo:
    image: "mongo:4"
    ports:
      - "27020:27017"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - ./worker/.env
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    volumes:
      - ./worker:/usr/src/app
      - /usr/src/app/node_modules
