version: '3'
services:
  express-app:
    build:
      context: ./server
      args:
        NODE_ENV: development
    ports:
      - "3002:3002"
    depends_on:
      - flask-app
      - redis
      - mongo
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://mongo:27017/AIsummarizer
      - REDISHOST=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev  

  flask-app:
    build: ./python-youtube-scraper
    volumes:
      - ./python-youtube-scraper:/usr/src/app
  redis:
    image: "redis:latest"

  mongo:
    image: "mongo:4"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"

  worker:
    build: ./worker
    depends_on:
      - rabbitmq
    env_file:
      - ./worker/.env
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    volumes:
      - ./worker:/usr/src/worker
