version: '3'
services:
  express-app:
    build: ./server
    ports:
      - "3002:3002"
    depends_on:
      - flask-app
      - redis
      - mongo
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://mongo:27017/AIsummarizer
      - REDISHOST=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq

    volumes:
      - ./server:/usr/src/app

  flask-app:
    build: ./python-youtube-scraper
    ports:
      - "5000:5000"
    volumes:
      - ./python-youtube-scraper:/usr/src/app
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
